name: init

on:
  push:
    paths:
      - 'config/main.sh'
      - 'compose/**'
      - 'scripts/**'
      - 'utils/**'
      - 'hosts'
      
jobs:
  init:
    runs-on: ubuntu-latest
    env:
      TERM: xterm
    defaults:
      run:
        shell: bash
        
    steps:
      - name: Initialize
        run: echo "hola"

      - name: docker-compose-version
        run: docker-compose-version

